# Copyright 2018 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM centos:7

MAINTAINER GoCD <go-cd-dev@googlegroups.com>

LABEL gocd.version="<%= gocd_version %>" \
  description="GoCD server based on CentOS 7" \
  maintainer="GoCD <go-cd-dev@googlegroups.com>" \
  gocd.full.version="<%= gocd_full_version %>" \
  gocd.git.sha="<%= gocd_git_sha %>"

# the ports that go server runs on
EXPOSE 8153 8154

# force encoding
ENV LANG=en_US.utf8

ARG UID=1000
ARG GID=1000

ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini-static-amd64 /usr/local/sbin/tini
ADD https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64 /usr/local/sbin/gosu

RUN \
  chmod 0755 /usr/local/sbin/tini && \
  chown root:root /usr/local/sbin/tini && \
  chmod 0755 /usr/local/sbin/gosu && \
  chown root:root /usr/local/sbin/gosu && \
# add our user and group first to make sure their IDs get assigned consistently,
# regardless of whatever dependencies get added
  groupadd -g ${GID} go && \
  useradd -u ${UID} -g go -d /home/go -m go && \
# install dependencies and other helpful CLI tools
  yum update -y && \
  yum install -y java-11-openjdk-headless git mercurial subversion openssh-clients bash unzip curl && \
  yum clean all && \
# download the zip file
  curl --fail --location --silent --show-error "<%= download_url %>" > /tmp/go-server.zip && \
# unzip the zip file into /go-server, after stripping the first path prefix
  unzip /tmp/go-server.zip -d / && \
  rm /tmp/go-server.zip && \
  mv go-server-<%= gocd_version %> /go-server && \
  mkdir -p /docker-entrypoint.d

COPY logback-include.xml /go-server/config/logback-include.xml
COPY install-gocd-plugins /usr/local/sbin/install-gocd-plugins
COPY git-clone-config /usr/local/sbin/git-clone-config

ADD docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
